name: Cypress Tests
on:
  workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          echo '${{ secrets.CYPRESS_ENV_JSON }}' > cypress.env.json
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          env:
            CYPRESS_name: ${{ secrets.name }}